.TH SaX3 0.2

.SH NAME
SaX3(openSUSE Advanced X Configuration Utility v3)

.SH DESCRIPTION
SaX3 provides a Graphical Utility for editing xorg.conf.d in a simplified manner so that users do not undergo the pain to modify configuration files. X currently, has automatic configuration but sometimes these configurations have to be manually overriden, in such cases SaX3 can be a useful tool.
.SH BUG REPORTING
Bugs can be reported at http://code.google.com/p/sax3/issues/entry

.SH AUTHOR
Manu Gupta and Michal Hrusuckey
